name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      gcp_job:
        required: true
        type: choice
        description: 'Directory of the job to (re-)deploy'
        options:
        - ocp-container-registry

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: tools    
    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    - run: |
        set -x
        docker version
        docker ps
        docker context ls
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - run: |
        set -x
        docker version
        docker ps
        docker context ls
        ls /var/run/
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -input=false
      working-directory: ${{ github.event.inputs.gcp_job }}
    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ${{ github.event.inputs.gcp_job }}
